import type { KeyRecord } from "./types";

export const initialKeys: KeyRecord[] = [
  {
    id: "key-42",
    number: "42",
    ring: "B",
    building: "Aréna municipal",
    address: "120, rue des Sports",
    door: "porte mécanique arrière",
    comment: "Accès prioritaire à la salle des compresseurs.",
    status: "disponible",
  },
  {
    id: "key-17",
    number: "17",
    ring: "A",
    building: "Hôtel de ville",
    address: "1, place Civique",
    door: "entrée employés nord",
    comment: "Ouvre aussi le local d'archives temporaire.",
    status: "sortie",
  },
  {
    id: "key-88",
    number: "88",
    ring: "C",
    building: "Garage municipal",
    address: "455, boulevard Industriel",
    door: "atelier voirie",
    comment: "Vérifier le barillet après chaque tempête majeure.",
    status: "à vérifier",
  },
  {
    id: "key-64",
    number: "64",
    ring: "D",
    building: "Bibliothèque centrale",
    address: "300, avenue du Parc",
    door: "local électrique sous-sol",
    comment: "Accès réservé aux interventions techniques.",
    status: "disponible",
  },
  {
    id: "key-09",
    number: "09",
    ring: "A",
    building: "Centre communautaire",
    address: "78, rue Principale",
    door: "salle polyvalente",
    comment: "Clé signalée manquante lors du dernier inventaire.",
    status: "perdue",
  },
  {
    id: "key-31",
    number: "31",
    ring: "B",
    building: "Usine de filtration",
    address: "910, chemin de l'Eau",
    door: "porte chloration",
    comment: "Appeler l'opérateur de garde avant d'entrer.",
    status: "disponible",
  },
];
